### ISSUE TITLE
Structs test cases have hard coded JSON values

### ISSUE THREAD

**Issue by karl-cardenas-coding** [karl-cardenas-coding/disaster-cli#32]
**Is your feature request related to a problem? Please describe.**
The structs test cases have hard coded JSON values.

**Describe the solution you'd like**
The test cases should pull the raw JSON down to confirm that no API changes breaks the strcuture

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by developerfred** [comment]
@karl-cardenas-coding would you like to test or json that api delivers without the raw data is it?

**Comment by karl-cardenas-coding** [comment]
@developerfred Rather than the hard coded JSON string, it should fetch a raw JSON from the API, 

such as https://eonet.sci.gsfc.nasa.gov/api/v3/events/EONET_4639. That way the test is more dynamic.

**Comment by developerfred** [comment]
@karl-cardenas-coding Thanks, I will do this.

**Comment by karl-cardenas-coding** [comment]
Awesome, thank you. I assigned you to the issue.
